apiVersion: v1
kind: Service
metadata:
  name: social
  labels:
    app: social
spec:
  selector:
    app.kubernetes.io/name: social
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9002
